on:
  push:

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        size: [1, 1024, $((1024*1024))]
      
    runs-on: ubuntu-latest

    env:
      IMAGE: ghcr.io/${{ github.repository }}

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.IMAGE }} --build-arg SIZE=${{ matrix.size }}
